### PR TITLE
[volumes]: improve create volume doc

### PR DESCRIPTION
**Pull request by drish**
* add driveropts object field
* move size and snapshot into driveropts object

### CODE REVIEW

**Comment by Gnep** [comment]
LGTM

**Comment by Gnep** [comment]
@carmark Pls review

**Comment by carmark** [comment]
@drish Could you please rebase this PR? I merged the previous PRs so this PR is conflict.

**Comment by drish** [comment]
@carmark done. 👍

**Comment by carmark** [comment]
LGTM, thanks.

**Pull request merged**
